1 : Intial Data Understanding

     * Data Loading and Inspection
     * Data Type
     *  Missing values = القيم المفقودة
     * Duplicates = القيم المكررة

In [1]:
print("hello,world!")

hello,world!

In [2]:
import pandas as pd 
data = pd.read_csv('car_price.csv')
data.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

data.shape :  خاصية تعطيك حجم الـ(عدد الصفوف, عدد الأعمدة)

In [3]:
data.shape

(2500, 10)

data.info() : 
       * DataFarme دالة تعطيك ملخصاً كاملاً عن الـ

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB

data.duplicated().sum() : دالة تعطيك عدد الصفوف المكررة

In [5]:
data.duplicated().sum()

np.int64(0)

2. Basic Statistical Overview
Summary Statistics (describe(), value_counts())
Zero and Constant Values

In [6]:
data.describe()

           Car ID       Year  Engine Size        Mileage         Price
count  2500.00000  2500.0000  2500.000000    2500.000000   2500.000000
mean   1250.50000  2011.6268     3.465240  149749.844800  52638.022532
std     721.83216     6.9917     1.432053   87919.952034  27295.833455
min       1.00000  2000.0000     1.000000      15.000000   5011.270000
25%     625.75000  2005.0000     2.200000   71831.500000  28908.485000
50%    1250.50000  2012.0000     3.400000  149085.000000  53485.240000
75%    1875.25000  2018.0000     4.700000  225990.500000  75838.532500
max    2500.00000  2023.0000     6.000000  299967.000000  99982.590000

In [7]:
data.isna().sum()

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64

In [8]:
data.drop_duplicates(inplace = True)
data.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

data.select_dtypes(include = 'object').describe() : 
يعطيك ملخصاً إحصائياً للأعمدة التي تحتوي على نصوص

In [9]:
data.select_dtypes(include = 'object').describe()

         Brand Fuel Type Transmission Condition   Model
count     2500      2500         2500      2500    2500
unique       7         4            2         3      28
top     Toyota    Diesel       Manual      Used  Fiesta
freq       374       655         1308       855     103

In [10]:
def top_and_bottom_combined(df, col, n=5):
    top_counts = df[col].value_counts().head(n)
    bottom_counts = df[col].value_counts().tail(n)
    
    combined = pd.concat([top_counts, bottom_counts], axis=0)
    return combined

for col in data.select_dtypes(include='object'):
    print(f'{col} value counts:')
    print(top_and_bottom_combined(data, col))
    print('30 Unique values:', data[col].unique()[:30])
    print('-------------------')

Brand value counts:
Brand
Toyota      374
Audi        368
BMW         358
Mercedes    353
Honda       352
BMW         358
Mercedes    353
Honda       352
Tesla       348
Ford        347
Name: count, dtype: int64
30 Unique values: ['Tesla' 'BMW' 'Audi' 'Ford' 'Honda' 'Mercedes' 'Toyota']
-------------------
Fuel Type value counts:
Fuel Type
Diesel      655
Petrol      630
Electric    614
Hybrid      601
Diesel      655
Petrol      630
Electric    614
Hybrid      601
Name: count, dtype: int64
30 Unique values: ['Petrol' 'Electric' 'Diesel' 'Hybrid']
-------------------
Transmission value counts:
Transmission
Manual       1308
Automatic    1192
Manual       1308
Automatic    1192
Name: count, dtype: int64
30 Unique values: ['Manual' 'Automatic']
-------------------
Condition value counts:
Condition
Used        855
Like New    836
New         809
Used        855
Like New    836
New         809
Name: count, dtype: int64
30 Unique values: ['New' 'Used' 'Like New']
-------------------
Model value counts:
Model
Fiesta     103
Corolla    103
A3          98
A4          96
Q7          95
X5          80
GLC         80
Q5          79
Model S     79
Mustang     77
Name: count, dtype: int64
30 Unique values: ['Model X' '5 Series' 'A4' 'Model Y' 'Mustang' 'Q7' 'Q5' 'Civic'
 'Explorer' 'Model 3' 'Fiesta' 'X3' 'GLA' 'A3' 'X5' 'C-Class' 'E-Class'
 'CR-V' 'Camry' 'Accord' 'GLC' 'Corolla' 'Fit' 'Model S' 'Prius'
 '3 Series' 'RAV4' 'Focus']
-------------------

In [11]:
data.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [13]:
print(data['Model'].unique())

['Model X' '5 Series' 'A4' 'Model Y' 'Mustang' 'Q7' 'Q5' 'Civic'
 'Explorer' 'Model 3' 'Fiesta' 'X3' 'GLA' 'A3' 'X5' 'C-Class' 'E-Class'
 'CR-V' 'Camry' 'Accord' 'GLC' 'Corolla' 'Fit' 'Model S' 'Prius'
 '3 Series' 'RAV4' 'Focus']

In [14]:
data.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   object
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   object
 5   Transmission  2500 non-null   object
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   object
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 195.4+ KB