In [528]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split # باش تقسم البيانات (تدريب واختبار)
from sklearn.linear_model import LinearRegression    # خوارزمية بسيطة للبدء
from sklearn.ensemble import RandomForestRegressor  # خوارزمية أقوى وأدق
from sklearn.metrics import mean_absolute_error      # باش تعرف شحال "غالط" الموديل في التوقع

In [529]:
data = pd.read_csv('./Lap 2.csv')
data.head()

,name,brand,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,cores,threads,warranty,image_url
0,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,Lenovo,67990.0,4.20,55.0,Windows 11 OS,13th Gen Intel Core i7 13620H,16 GB LPDDR5 RAM,512 GB SSD,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,10 Cores (6P + 4E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-i1fsJnGQg-w280-h...
1,Asus Vivobook 14 S3407CA-LY084WS Laptop (Intel...,Asus,82990.0,4.55,68.0,Windows 11 OS,Intel Core Ultra 7 255H,16 GB DDR5 RAM,512 GB SSD,Intel Integrated Intel,14 inches,1920 x 1200 pixels,16 Cores (6P + 8E + 2LP-E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iNaorM7Pv-w280-h...
2,Acer Aspire Lite AL15-52H Laptop (12th Gen Cor...,Acer,36541.0,4.75,56.0,Windows 11 OS,12th Gen Intel Core i5 12450H,16 GB DDR4 RAM,512 GB SSD,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,Octa Core (4P + 4E),12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iDIxx1KCW-w280-h...
3,HP Victus 15-fb3012AX Gaming Laptop (AMD Ryzen...,HP,65990.0,4.10,72.0,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16 GB DDR5 RAM,512 GB SSD,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,Hexa Core,12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-ifsyyr3XR-w280-h...
4,Apple MacBook Air 2022 Laptop (Apple M2/ 16GB/...,Apple,66990.0,4.15,NaN,Mac OS,Apple M2,16 GB Unified Memory RAM,256 GB SSD,10-Core GPU,13.6 inches,2560 x 1664 pixels,Octa Core,NaN,1 Year Warranty,https://cdn1.smartprix.com/rx-iD0cxZkFL-w280-h...

In [530]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         1011 non-null   object
 1   brand        1011 non-null   object
 2   price        1011 non-null   float64
 3   ratings      1011 non-null   float64
 4   specs_score  819 non-null    float64
 5   os           1007 non-null   object
 6   processor    1011 non-null   object
 7   ram          1011 non-null   object
 8   storage      1011 non-null   object
 9   graphics     1011 non-null   object
 10  screen_size  1011 non-null   object
 11  resoultion   987 non-null    object
 12  cores        1011 non-null   object
 13  threads      921 non-null    object
 14  warranty     1006 non-null   object
 15  image_url    1011 non-null   object
dtypes: float64(3), object(13)
memory usage: 126.5+ KB

In [531]:
data.isna().sum

<bound method DataFrame.sum of        name  brand  price  ratings  specs_score     os  processor    ram  \
0     False  False  False    False        False  False      False  False
1     False  False  False    False        False  False      False  False
2     False  False  False    False        False  False      False  False
3     False  False  False    False        False  False      False  False
4     False  False  False    False         True  False      False  False
...     ...    ...    ...      ...          ...    ...        ...    ...
1006  False  False  False    False         True  False      False  False
1007  False  False  False    False         True  False      False  False
1008  False  False  False    False        False  False      False  False
1009  False  False  False    False        False  False      False  False
1010  False  False  False    False        False  False      False  False

      storage  graphics  screen_size  resoultion  cores  threads  warranty  \
0       False     False        False       False  False    False     False
1       False     False        False       False  False    False     False
2       False     False        False       False  False    False     False
3       False     False        False       False  False    False     False
4       False     False        False       False  False     True     False
...       ...       ...          ...         ...    ...      ...       ...
1006    False     False        False       False  False    False     False
1007    False     False        False       False  False    False     False
1008    False     False        False       False  False    False     False
1009    False     False        False       False  False    False     False
1010    False     False        False       False  False    False     False

      image_url
0         False
1         False
2         False
3         False
4         False
...         ...
1006      False
1007      False
1008      False
1009      False
1010      False

[1011 rows x 16 columns]>

In [532]:
data.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
1006    False
1007    False
1008    False
1009    False
1010    False
Length: 1011, dtype: bool>

In [533]:
data.shape

(1011, 16)

In [534]:
data.drop_duplicates(inplace=True)
data.shape

(1001, 16)

In [535]:
data.describe()

               price      ratings  specs_score
count    1001.000000  1001.000000   810.000000
mean    83256.870130     4.370080    60.695062
std     68692.847348     0.231325     7.328229
min      9999.000000     4.000000    50.000000
25%     43400.000000     4.150000    54.000000
50%     64990.000000     4.350000    60.000000
75%     91990.000000     4.550000    66.000000
max    617990.000000     4.750000    79.000000

In [536]:
data.select_dtypes(include='object').describe()

,name,brand,os,processor,ram,storage,graphics,screen_size,resoultion,cores,threads,warranty,image_url
count,1001,1001,997,1001,1001,1001,1001,1001,977,1001,912,996,1001
unique,1001,26,13,197,57,28,153,28,24,37,14,8,974
top,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,HP,Windows 11 OS,13th Gen Intel Core i5 13420H,16 GB DDR4 RAM,512 GB SSD,Intel Integrated UHD,15.6 inches,1920 x 1080 pixels,Octa Core (4P + 4E),12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iBBZ9nHbC-w280-h...
freq,1,237,892,61,214,672,82,477,568,138,321,888,3

In [537]:
data['specs_score'] = data['specs_score'].fillna(data['specs_score'].mean())
data.head()

,name,brand,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,cores,threads,warranty,image_url
0,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,Lenovo,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16 GB LPDDR5 RAM,512 GB SSD,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,10 Cores (6P + 4E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-i1fsJnGQg-w280-h...
1,Asus Vivobook 14 S3407CA-LY084WS Laptop (Intel...,Asus,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16 GB DDR5 RAM,512 GB SSD,Intel Integrated Intel,14 inches,1920 x 1200 pixels,16 Cores (6P + 8E + 2LP-E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iNaorM7Pv-w280-h...
2,Acer Aspire Lite AL15-52H Laptop (12th Gen Cor...,Acer,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16 GB DDR4 RAM,512 GB SSD,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,Octa Core (4P + 4E),12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iDIxx1KCW-w280-h...
3,HP Victus 15-fb3012AX Gaming Laptop (AMD Ryzen...,HP,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16 GB DDR5 RAM,512 GB SSD,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,Hexa Core,12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-ifsyyr3XR-w280-h...
4,Apple MacBook Air 2022 Laptop (Apple M2/ 16GB/...,Apple,66990.0,4.15,60.695062,Mac OS,Apple M2,16 GB Unified Memory RAM,256 GB SSD,10-Core GPU,13.6 inches,2560 x 1664 pixels,Octa Core,NaN,1 Year Warranty,https://cdn1.smartprix.com/rx-iD0cxZkFL-w280-h...

In [538]:
#data["ram"] = data["ram"].str.replace("GB" , "" , case=False)
#data["ram"] = data["ram"].str.replace("RAM" , "" , case=False)
#data['ram'] = data['ram'].str.extract(r'(\d+)')
#data['ram'] = pd.to_numeric(data['ram'], errors='coerce')
#data = data.dropna(subset=['ram'])
#data['ram'] = data['ram'].astype(int)

#print(data['ram'].dtype)

In [539]:
if data['ram'].dtype == 'object':
    data['ram'] = data['ram'].astype(str).str.extract(r'(\d+)')
    data['ram'] = pd.to_numeric(data['ram'], errors='coerce')
    data = data.dropna(subset=['ram'])
    data['ram'] = data['ram'].astype(int)

print(f"النوع الحالي: {data['ram'].dtype}")
data.head()

النوع الحالي: int64

,name,brand,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,cores,threads,warranty,image_url
0,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,Lenovo,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512 GB SSD,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,10 Cores (6P + 4E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-i1fsJnGQg-w280-h...
1,Asus Vivobook 14 S3407CA-LY084WS Laptop (Intel...,Asus,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16,512 GB SSD,Intel Integrated Intel,14 inches,1920 x 1200 pixels,16 Cores (6P + 8E + 2LP-E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iNaorM7Pv-w280-h...
2,Acer Aspire Lite AL15-52H Laptop (12th Gen Cor...,Acer,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512 GB SSD,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,Octa Core (4P + 4E),12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iDIxx1KCW-w280-h...
3,HP Victus 15-fb3012AX Gaming Laptop (AMD Ryzen...,HP,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512 GB SSD,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,Hexa Core,12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-ifsyyr3XR-w280-h...
4,Apple MacBook Air 2022 Laptop (Apple M2/ 16GB/...,Apple,66990.0,4.15,60.695062,Mac OS,Apple M2,16,256 GB SSD,10-Core GPU,13.6 inches,2560 x 1664 pixels,Octa Core,NaN,1 Year Warranty,https://cdn1.smartprix.com/rx-iD0cxZkFL-w280-h...

In [540]:
if data['storage'].dtype == 'object':
    data['storage'] = data['storage'].astype(str).str.extract(r'(\d+)')
    data['storage'] = pd.to_numeric(data['storage'], errors='coerce')
    data = data.dropna(subset=['storage'])
    data['storage'] = data['storage'].astype(int)

print( data['storage'].dtype)
data.head()

int64

,name,brand,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,cores,threads,warranty,image_url
0,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,Lenovo,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,10 Cores (6P + 4E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-i1fsJnGQg-w280-h...
1,Asus Vivobook 14 S3407CA-LY084WS Laptop (Intel...,Asus,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,1920 x 1200 pixels,16 Cores (6P + 8E + 2LP-E),16 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iNaorM7Pv-w280-h...
2,Acer Aspire Lite AL15-52H Laptop (12th Gen Cor...,Acer,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,Octa Core (4P + 4E),12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-iDIxx1KCW-w280-h...
3,HP Victus 15-fb3012AX Gaming Laptop (AMD Ryzen...,HP,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,Hexa Core,12 Threads,1 Year Warranty,https://cdn1.smartprix.com/rx-ifsyyr3XR-w280-h...
4,Apple MacBook Air 2022 Laptop (Apple M2/ 16GB/...,Apple,66990.0,4.15,60.695062,Mac OS,Apple M2,16,256,10-Core GPU,13.6 inches,2560 x 1664 pixels,Octa Core,NaN,1 Year Warranty,https://cdn1.smartprix.com/rx-iD0cxZkFL-w280-h...

In [541]:
brand_counts = data["brand"].value_counts()
print(brand_counts)

brand
HP           234
Lenovo       204
Asus         162
Acer         124
MSI           94
Dell          57
Apple         36
Samsung       15
Infinix       14
Gigabyte       8
Microsoft      7
Ultimus        6
Motorola       5
Primebook      5
Chuwi          3
Thomson        3
Alienware      3
Walker         2
Avita          2
ASUS           1
Zebronics      1
Jio            1
Colorful       1
Wings          1
AXL            1
Name: count, dtype: int64

In [542]:
majour_brand = brand_counts[brand_counts>=10].index
data["brand"] = data["brand"].apply(lambda x : x if x in majour_brand else 'other')
data["brand"].unique()

array(['Lenovo', 'Asus', 'Acer', 'HP', 'Apple', 'other', 'Dell',
       'Infinix', 'MSI', 'Samsung'], dtype=object)

In [543]:
data = pd.get_dummies(data,columns=['brand'],prefix="brand")
data.head()

,name,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,...,brand_Acer,brand_Apple,brand_Asus,brand_Dell,brand_HP,brand_Infinix,brand_Lenovo,brand_MSI,brand_Samsung,brand_other
0,Lenovo IdeaPad Slim 3 83K100CJIN Laptop (13th ...,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,...,False,False,False,False,False,False,True,False,False,False
1,Asus Vivobook 14 S3407CA-LY084WS Laptop (Intel...,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,...,False,False,True,False,False,False,False,False,False,False
2,Acer Aspire Lite AL15-52H Laptop (12th Gen Cor...,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,...,True,False,False,False,False,False,False,False,False,False
3,HP Victus 15-fb3012AX Gaming Laptop (AMD Ryzen...,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,...,False,False,False,False,True,False,False,False,False,False
4,Apple MacBook Air 2022 Laptop (Apple M2/ 16GB/...,66990.0,4.15,60.695062,Mac OS,Apple M2,16,256,10-Core GPU,13.6 inches,...,False,True,False,False,False,False,False,False,False,False

In [544]:
data.drop('name' , axis=1 , inplace=True)
data.head()

,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,...,brand_Acer,brand_Apple,brand_Asus,brand_Dell,brand_HP,brand_Infinix,brand_Lenovo,brand_MSI,brand_Samsung,brand_other
0,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,...,False,False,False,False,False,False,True,False,False,False
1,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,1920 x 1200 pixels,...,False,False,True,False,False,False,False,False,False,False
2,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,...,True,False,False,False,False,False,False,False,False,False
3,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,...,False,False,False,False,True,False,False,False,False,False
4,66990.0,4.15,60.695062,Mac OS,Apple M2,16,256,10-Core GPU,13.6 inches,2560 x 1664 pixels,...,False,True,False,False,False,False,False,False,False,False

In [545]:
print(data["processor"].value_counts().head(20))

processor
13th Gen Intel Core i5 13420H       61
13th Gen Intel Core i7 13620H       38
12th Gen Intel Core i5 1235U        38
12th Gen Intel Core i5 12450H       35
13th Gen Intel Core i3 1315U        34
13th Gen Intel Core i5 1334U        30
12th Gen Intel Core i3 1215U        28
7th Gen AMD Ryzen 5 7520U           21
Intel Core Ultra 5 Series 1 125H    17
13th Gen Intel Core i5 1335U        17
Intel Core Ultra 7 Series 1 155H    16
14th Gen Intel Core i7 14650HX      16
Intel Core Ultra 9 275HX            16
7th Gen AMD Ryzen 5 7530U           16
Intel Celeron N4500                 15
7th Gen AMD Ryzen 3 7320U           13
13th Gen Intel Core i7 13650HX      13
7th Gen AMD Ryzen 5 7535HS          12
12th Gen Intel Core i5 12450HX      11
7th Gen AMD Ryzen 7 7730U           11
Name: count, dtype: int64

In [546]:
def process_cpu(text):
    text = str(text).lower()
    
    # Intel High-End
    if 'i7' in text or 'i9' in text or 'ultra 7' in text or 'ultra 9' in text:
        return 'Intel High-End'
    # Intel Mid-Range
    elif 'i5' in text or 'ultra 5' in text:
        return 'Intel Mid-Range'
    # Intel Entry-Level
    elif 'i3' in text:
        return 'Intel i3'
    # AMD High-End
    elif 'ryzen 7' in text or 'ryzen 9' in text:
        return 'AMD High-End'
    # AMD Mid-Range
    elif 'ryzen 5' in text:
        return 'AMD Ryzen 5'
    # AMD Entry-Level
    elif 'ryzen 3' in text:
        return 'AMD Ryzen 3'
    # Budget Processors (Celeron, Pentium, etc.)
    elif 'celeron' in text or 'pentium' in text or 'athlon' in text:
        return 'Budget CPU'
    else:
        return 'Other'

# تطبيق الدالة على العمود
data['cpu_brand'] = data['processor'].apply(process_cpu)

In [547]:
data = pd.get_dummies(data,columns=["cpu_brand"] , prefix="cpu")
data.head()

,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,...,brand_Samsung,brand_other,cpu_AMD High-End,cpu_AMD Ryzen 3,cpu_AMD Ryzen 5,cpu_Budget CPU,cpu_Intel High-End,cpu_Intel Mid-Range,cpu_Intel i3,cpu_Other
0,67990.0,4.20,55.000000,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,...,False,False,False,False,False,False,True,False,False,False
1,82990.0,4.55,68.000000,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,1920 x 1200 pixels,...,False,False,False,False,False,False,True,False,False,False
2,36541.0,4.75,56.000000,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,...,False,False,False,False,False,False,False,True,False,False
3,65990.0,4.10,72.000000,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,...,False,False,False,False,True,False,False,False,False,False
4,66990.0,4.15,60.695062,Mac OS,Apple M2,16,256,10-Core GPU,13.6 inches,2560 x 1664 pixels,...,False,False,False,False,False,False,False,False,False,True

In [548]:
print(data["os"].value_counts().head())

os
Windows 11 OS      892
Mac OS              36
DOS OS              22
Chrome OS           13
1 Year Warranty     10
Name: count, dtype: int64

In [549]:
def process_os(text):
    text = str(text).lower()
    if "windows" in text:
        return "windows"
    elif "Mac" in text:
        return "Mac"
    elif "DOS" in text:
        return "DOS/No OS"
    else:
        return 'Others'
    
data["os_type"] = data["os"].apply(process_os)
data = data[data["os_type"] != "Others"]

In [550]:
data = pd.get_dummies(data,columns=["os_type"],prefix="os")
data.head()

,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,...,brand_other,cpu_AMD High-End,cpu_AMD Ryzen 3,cpu_AMD Ryzen 5,cpu_Budget CPU,cpu_Intel High-End,cpu_Intel Mid-Range,cpu_Intel i3,cpu_Other,os_windows
0,67990.0,4.20,55.0,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,...,False,False,False,False,False,True,False,False,False,True
1,82990.0,4.55,68.0,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,1920 x 1200 pixels,...,False,False,False,False,False,True,False,False,False,True
2,36541.0,4.75,56.0,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,...,False,False,False,False,False,False,True,False,False,True
3,65990.0,4.10,72.0,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,...,False,False,False,True,False,False,False,False,False,True
5,35490.0,4.35,61.0,Windows 11 OS,7th Gen AMD Ryzen 5 7520U,16,512,Integrated AMD Radeon 610M Graphics,15.6 inches,1920 x 1080 pixels,...,False,False,False,True,False,False,False,False,False,True

In [551]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1010
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                898 non-null    float64
 1   ratings              898 non-null    float64
 2   specs_score          898 non-null    float64
 3   os                   898 non-null    object
 4   processor            898 non-null    object
 5   ram                  898 non-null    int64
 6   storage              898 non-null    int64
 7   graphics             898 non-null    object
 8   screen_size          898 non-null    object
 9   resoultion           898 non-null    object
 10  cores                898 non-null    object
 11  threads              873 non-null    object
 12  warranty             898 non-null    object
 13  image_url            898 non-null    object
 14  brand_Acer           898 non-null    bool
 15  brand_Apple          898 non-null    bool
 16  brand_Asus           898 non-null    bool
 17  brand_Dell           898 non-null    bool
 18  brand_HP             898 non-null    bool
 19  brand_Infinix        898 non-null    bool
 20  brand_Lenovo         898 non-null    bool
 21  brand_MSI            898 non-null    bool
 22  brand_Samsung        898 non-null    bool
 23  brand_other          898 non-null    bool
 24  cpu_AMD High-End     898 non-null    bool
 25  cpu_AMD Ryzen 3      898 non-null    bool
 26  cpu_AMD Ryzen 5      898 non-null    bool
 27  cpu_Budget CPU       898 non-null    bool
 28  cpu_Intel High-End   898 non-null    bool
 29  cpu_Intel Mid-Range  898 non-null    bool
 30  cpu_Intel i3         898 non-null    bool
 31  cpu_Other            898 non-null    bool
 32  os_windows           898 non-null    bool
dtypes: bool(19), float64(3), int64(2), object(9)
memory usage: 121.9+ KB

In [552]:
data['cores'] = data['cores'].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

data['threads'] = data['threads'].astype(str).str.extract(r'(\d+)').fillna(0).astype(int)

print(data[['cores', 'threads']].dtypes)
data.head()

cores      int64
threads    int64
dtype: object

,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,...,brand_other,cpu_AMD High-End,cpu_AMD Ryzen 3,cpu_AMD Ryzen 5,cpu_Budget CPU,cpu_Intel High-End,cpu_Intel Mid-Range,cpu_Intel i3,cpu_Other,os_windows
0,67990.0,4.20,55.0,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28 inches,1920 x 1080 pixels,...,False,False,False,False,False,True,False,False,False,True
1,82990.0,4.55,68.0,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14 inches,1920 x 1200 pixels,...,False,False,False,False,False,True,False,False,False,True
2,36541.0,4.75,56.0,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.6 inches,1920 x 1080 pixels,...,False,False,False,False,False,False,True,False,False,True
3,65990.0,4.10,72.0,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.6 inches,1920 x 1080 pixels,...,False,False,False,True,False,False,False,False,False,True
5,35490.0,4.35,61.0,Windows 11 OS,7th Gen AMD Ryzen 5 7520U,16,512,Integrated AMD Radeon 610M Graphics,15.6 inches,1920 x 1080 pixels,...,False,False,False,True,False,False,False,False,False,True

In [553]:
data['screen_size'] = data['screen_size'].astype(str).str.extract(r'(\d+\.?\d*)').astype(float)

print("نوع حجم الشاشة:", data['screen_size'].dtype)

نوع حجم الشاشة: float64

In [554]:
data['resoultion'] = data['resoultion'].astype(str).str.extract(r'(\d+)').astype(float)

In [555]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1010
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                898 non-null    float64
 1   ratings              898 non-null    float64
 2   specs_score          898 non-null    float64
 3   os                   898 non-null    object
 4   processor            898 non-null    object
 5   ram                  898 non-null    int64
 6   storage              898 non-null    int64
 7   graphics             898 non-null    object
 8   screen_size          898 non-null    float64
 9   resoultion           898 non-null    float64
 10  cores                898 non-null    int64
 11  threads              898 non-null    int64
 12  warranty             898 non-null    object
 13  image_url            898 non-null    object
 14  brand_Acer           898 non-null    bool
 15  brand_Apple          898 non-null    bool
 16  brand_Asus           898 non-null    bool
 17  brand_Dell           898 non-null    bool
 18  brand_HP             898 non-null    bool
 19  brand_Infinix        898 non-null    bool
 20  brand_Lenovo         898 non-null    bool
 21  brand_MSI            898 non-null    bool
 22  brand_Samsung        898 non-null    bool
 23  brand_other          898 non-null    bool
 24  cpu_AMD High-End     898 non-null    bool
 25  cpu_AMD Ryzen 3      898 non-null    bool
 26  cpu_AMD Ryzen 5      898 non-null    bool
 27  cpu_Budget CPU       898 non-null    bool
 28  cpu_Intel High-End   898 non-null    bool
 29  cpu_Intel Mid-Range  898 non-null    bool
 30  cpu_Intel i3         898 non-null    bool
 31  cpu_Other            898 non-null    bool
 32  os_windows           898 non-null    bool
dtypes: bool(19), float64(5), int64(4), object(5)
memory usage: 121.9+ KB

In [556]:
data.drop('image_url', axis=1, inplace=True)
data.head()

,price,ratings,specs_score,os,processor,ram,storage,graphics,screen_size,resoultion,...,brand_other,cpu_AMD High-End,cpu_AMD Ryzen 3,cpu_AMD Ryzen 5,cpu_Budget CPU,cpu_Intel High-End,cpu_Intel Mid-Range,cpu_Intel i3,cpu_Other,os_windows
0,67990.0,4.20,55.0,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,Integrated Intel UHD Graphics,15.28,1920.0,...,False,False,False,False,False,True,False,False,False,True
1,82990.0,4.55,68.0,Windows 11 OS,Intel Core Ultra 7 255H,16,512,Intel Integrated Intel,14.00,1920.0,...,False,False,False,False,False,True,False,False,False,True
2,36541.0,4.75,56.0,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,Intel UHD Graphics,15.60,1920.0,...,False,False,False,False,False,False,True,False,False,True
3,65990.0,4.10,72.0,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,6 GB NVIDIA GeForce RTX 3050,15.60,1920.0,...,False,False,False,True,False,False,False,False,False,True
5,35490.0,4.35,61.0,Windows 11 OS,7th Gen AMD Ryzen 5 7520U,16,512,Integrated AMD Radeon 610M Graphics,15.60,1920.0,...,False,False,False,True,False,False,False,False,False,True

In [557]:
# 1. حول لـ string أولا
data['warranty'] = data['warranty'].astype(str)

# 2. جبد الرقم (1 أو 2 أو 3...)
data['warranty'] = data['warranty'].str.extract(r'(\d+)')

# 3. حول الأرقام لـ float أولا باش نتعاملو مع القيم الخاوية
data['warranty'] = pd.to_numeric(data['warranty'], errors='coerce')

# 4. أي حاسوب ما مكتوبش فيه الضمان (NaN) نعتبروه 0 سنين ضمان
data['warranty'] = data['warranty'].fillna(0).astype(int)

print("قيم الضمان اللي عندك دابا:", data['warranty'].unique())

قيم الضمان اللي عندك دابا: [1 2 0 3]

In [558]:
print(data['graphics'].value_counts().head(10))

graphics
Intel Integrated UHD            72
6 GB NVIDIA GeForce RTX 4050    55
6 GB NVIDIA GeForce RTX 3050    54
AMD Radeon Graphics             48
Intel UHD Graphics              46
AMD Radeon AMD                  39
Intel Integrated Iris Xe        35
4 GB NVIDIA GeForce RTX 2050    34
4 GB NVIDIA GeForce RTX 3050    32
8 GB NVIDIA GeForce RTX 4060    32
Name: count, dtype: int64

In [559]:
# 1. نجبدو الماركة (Nvidia, Intel, AMD) ونكريو ليها أعمدة (Encoding)
data['nividia_gpu'] = data['graphics'].str.contains('NVIDIA', case=False).astype(int)
data['amd_gpu'] = data['graphics'].str.contains('AMD|Radeon', case=False).astype(int)
data['intel_gpu'] = data['graphics'].str.contains('Intel', case=False).astype(int)

# 2. نجبدو سعة الذاكرة (VRAM) لي هي مثلا 4GB ولا 6GB
# غادي نقلبو على الرقم اللي تابعاه كلمة GB وسط عمود graphics
data['gpu_vram'] = data['graphics'].str.extract(r'(\d+)\s?GB').fillna(0).astype(int)

# 3. دابا نمسحو العمود الأصلي حيت مابقاش محتاجينه
data.drop('graphics', axis=1, inplace=True)

print(data[['nividia_gpu', 'amd_gpu', 'intel_gpu', 'gpu_vram']].head())

   nividia_gpu  amd_gpu  intel_gpu  gpu_vram
0            0        0          1         0
1            0        0          1         0
2            0        0          1         0
3            1        0          0         6
5            0        1          0         0

In [560]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1010
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                898 non-null    float64
 1   ratings              898 non-null    float64
 2   specs_score          898 non-null    float64
 3   os                   898 non-null    object
 4   processor            898 non-null    object
 5   ram                  898 non-null    int64
 6   storage              898 non-null    int64
 7   screen_size          898 non-null    float64
 8   resoultion           898 non-null    float64
 9   cores                898 non-null    int64
 10  threads              898 non-null    int64
 11  warranty             898 non-null    int64
 12  brand_Acer           898 non-null    bool
 13  brand_Apple          898 non-null    bool
 14  brand_Asus           898 non-null    bool
 15  brand_Dell           898 non-null    bool
 16  brand_HP             898 non-null    bool
 17  brand_Infinix        898 non-null    bool
 18  brand_Lenovo         898 non-null    bool
 19  brand_MSI            898 non-null    bool
 20  brand_Samsung        898 non-null    bool
 21  brand_other          898 non-null    bool
 22  cpu_AMD High-End     898 non-null    bool
 23  cpu_AMD Ryzen 3      898 non-null    bool
 24  cpu_AMD Ryzen 5      898 non-null    bool
 25  cpu_Budget CPU       898 non-null    bool
 26  cpu_Intel High-End   898 non-null    bool
 27  cpu_Intel Mid-Range  898 non-null    bool
 28  cpu_Intel i3         898 non-null    bool
 29  cpu_Other            898 non-null    bool
 30  os_windows           898 non-null    bool
 31  nividia_gpu          898 non-null    int64
 32  amd_gpu              898 non-null    int64
 33  intel_gpu            898 non-null    int64
 34  gpu_vram             898 non-null    int64
dtypes: bool(19), float64(5), int64(9), object(2)
memory usage: 135.9+ KB

In [561]:
data.head()

,price,ratings,specs_score,os,processor,ram,storage,screen_size,resoultion,cores,...,cpu_Budget CPU,cpu_Intel High-End,cpu_Intel Mid-Range,cpu_Intel i3,cpu_Other,os_windows,nividia_gpu,amd_gpu,intel_gpu,gpu_vram
0,67990.0,4.20,55.0,Windows 11 OS,13th Gen Intel Core i7 13620H,16,512,15.28,1920.0,10,...,False,True,False,False,False,True,0,0,1,0
1,82990.0,4.55,68.0,Windows 11 OS,Intel Core Ultra 7 255H,16,512,14.00,1920.0,16,...,False,True,False,False,False,True,0,0,1,0
2,36541.0,4.75,56.0,Windows 11 OS,12th Gen Intel Core i5 12450H,16,512,15.60,1920.0,4,...,False,False,True,False,False,True,0,0,1,0
3,65990.0,4.10,72.0,Windows 11 OS,8th Gen AMD Ryzen 5 8645HS,16,512,15.60,1920.0,0,...,False,False,False,False,False,True,1,0,0,6
5,35490.0,4.35,61.0,Windows 11 OS,7th Gen AMD Ryzen 5 7520U,16,512,15.60,1920.0,0,...,False,False,False,False,False,True,0,1,0,0

In [562]:
# kay5ali t3raf al A3mida li ba9yin object 
print(data.select_dtypes(include=['object']).columns)

Index(['os', 'processor'], dtype='object')

In [563]:
# كنشوفو الماركات اللي كاينين
print(data['os'].value_counts())

# أحسن طريقة هي One-Hot Encoding (كنردو كل نظام عمود فيه 0 و 1)
data = pd.get_dummies(data, columns=['os'], prefix='os')

os
Windows 11 OS     892
Windows 11  OS      3
Windows OS          2
Windows 10 OS       1
Name: count, dtype: int64

In [564]:
print(data.select_dtypes(include=['object']).columns)

Index(['processor'], dtype='object')

In [565]:
def simplify_cpu(text):
    text = str(text).lower()
    if 'i3' in text: return 'i3'
    if 'i5' in text: return 'i5'
    if 'i7' in text: return 'i7'
    if 'i9' in text: return 'i9'
    if 'ryzen 3' in text: return 'Ryzen 3'
    if 'ryzen 5' in text: return 'Ryzen 5'
    if 'ryzen 7' in text: return 'Ryzen 7'
    if 'ryzen 9' in text: return 'Ryzen 9'
    if 'm1' in text or 'm2' in text or 'm3' in text: return 'Apple Silicon'
    return 'Other'

# كنطبقو هاد الدالة على العمود
data['cpu_brand'] = data['processor'].apply(simplify_cpu)

# دابا نحولو هاد الماركات الجديدة لأرقام (One-Hot Encoding)
data = pd.get_dummies(data, columns=['cpu_brand'], prefix='cpu')

# ونمسحو عمود processor الأصلي
data.drop('processor', axis=1, inplace=True)

In [566]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 898 entries, 0 to 1010
Data columns (total 46 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                898 non-null    float64
 1   ratings              898 non-null    float64
 2   specs_score          898 non-null    float64
 3   ram                  898 non-null    int64
 4   storage              898 non-null    int64
 5   screen_size          898 non-null    float64
 6   resoultion           898 non-null    float64
 7   cores                898 non-null    int64
 8   threads              898 non-null    int64
 9   warranty             898 non-null    int64
 10  brand_Acer           898 non-null    bool
 11  brand_Apple          898 non-null    bool
 12  brand_Asus           898 non-null    bool
 13  brand_Dell           898 non-null    bool
 14  brand_HP             898 non-null    bool
 15  brand_Infinix        898 non-null    bool
 16  brand_Lenovo         898 non-null    bool
 17  brand_MSI            898 non-null    bool
 18  brand_Samsung        898 non-null    bool
 19  brand_other          898 non-null    bool
 20  cpu_AMD High-End     898 non-null    bool
 21  cpu_AMD Ryzen 3      898 non-null    bool
 22  cpu_AMD Ryzen 5      898 non-null    bool
 23  cpu_Budget CPU       898 non-null    bool
 24  cpu_Intel High-End   898 non-null    bool
 25  cpu_Intel Mid-Range  898 non-null    bool
 26  cpu_Intel i3         898 non-null    bool
 27  cpu_Other            898 non-null    bool
 28  os_windows           898 non-null    bool
 29  nividia_gpu          898 non-null    int64
 30  amd_gpu              898 non-null    int64
 31  intel_gpu            898 non-null    int64
 32  gpu_vram             898 non-null    int64
 33  os_Windows 10 OS     898 non-null    bool
 34  os_Windows 11  OS    898 non-null    bool
 35  os_Windows 11 OS     898 non-null    bool
 36  os_Windows OS        898 non-null    bool
 37  cpu_Other            898 non-null    bool
 38  cpu_Ryzen 3          898 non-null    bool
 39  cpu_Ryzen 5          898 non-null    bool
 40  cpu_Ryzen 7          898 non-null    bool
 41  cpu_Ryzen 9          898 non-null    bool
 42  cpu_i3               898 non-null    bool
 43  cpu_i5               898 non-null    bool
 44  cpu_i7               898 non-null    bool
 45  cpu_i9               898 non-null    bool
dtypes: bool(32), float64(5), int64(9)
memory usage: 133.3 KB

In [567]:
data.head()

,price,ratings,specs_score,ram,storage,screen_size,resoultion,cores,threads,warranty,...,os_Windows OS,cpu_Other,cpu_Ryzen 3,cpu_Ryzen 5,cpu_Ryzen 7,cpu_Ryzen 9,cpu_i3,cpu_i5,cpu_i7,cpu_i9
0,67990.0,4.20,55.0,16,512,15.28,1920.0,10,16,1,...,False,False,False,False,False,False,False,False,True,False
1,82990.0,4.55,68.0,16,512,14.00,1920.0,16,16,1,...,False,True,False,False,False,False,False,False,False,False
2,36541.0,4.75,56.0,16,512,15.60,1920.0,4,12,1,...,False,False,False,False,False,False,False,True,False,False
3,65990.0,4.10,72.0,16,512,15.60,1920.0,0,12,1,...,False,False,False,True,False,False,False,False,False,False
5,35490.0,4.35,61.0,16,512,15.60,1920.0,0,8,1,...,False,False,False,True,False,False,False,False,False,False

In [568]:
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

# 1. تحميل الداتا
df = pd.read_csv('Lap 2.csv')

# 2. تحويل النصوص لأرقام (ضروري باش الموديل يخدم)
df_encoded = pd.get_dummies(df)

# 3. فصل "الثمن" عن "المواصفات"
X = df_encoded.drop('price', axis=1) 
y = np.log1p(df_encoded['price']) # باش نحسبو اللوغاريتم

# 4. السكالينغ (الميزان)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 5. تدريب الموديل
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_scaled, y)

# 6. حفظ الملفات (هنا فين غيبانو الملفات اللي مسحتي دابا)
joblib.dump(model, 'laptop_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.tolist(), 'model_columns.pkl')

print("✅ الملفات تساوبو دابا! عاود دير 'ls' في Terminal غتلقاهم.")

✅ الملفات تساوبو دابا! عاود دير 'ls' في Terminal غتلقاهم.